config/routes.rb
# Page titles on Wikipedia may include dots, so this constraint is needed.

Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  # Sessions
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    get 'sign_out', to: 'users#signout', as: :destroy_user_session
    get 'sign_out_oauth', to: 'devise/sessions#destroy',
                          as: :true_destroy_user_session
  end

  # Users
  controller :users do
    get 'users/revisions' => 'users#revisions', :as => :user_revisions
  end

  resources :assignments

  # Self-enrollment: joining a course by entering a passcode or visiting a url
  get 'courses/:course_id/enroll/:passcode' => 'self_enrollment#enroll_self',
      constraints: { course_id: /.*/ }

  # Courses
  controller :courses do
    get 'courses/*id/get_wiki_top_section' => 'courses#get_wiki_top_section',
        :as => :get_wiki_top_section, constraints: { id: /.*/ }
    get 'courses/new' => 'courses#new',
        constraints: { id: /.*/ } # repeat of resources

    get 'courses/*id/manual_update' => 'courses#manual_update',
        :as => :manual_update, constraints: { id: /.*/ }
    get 'courses/*id/notify_untrained' => 'courses#notify_untrained',
        :as => :notify_untrained, constraints: { id: /.*/ }
    get 'courses/*id/notify_students(/:type)' => 'courses#notify_students',
        :as => :notify_students, constraints: { id: /.*/ }
    get 'courses/*id/update_course_talk' => 'courses#update_course_talk',
        :as => :update_course_talk, constraints: { id: /.*/ }

    get 'courses/*id/check' => 'courses#check',
        :as => :check, constraints: { id: /.*/ }
    match 'courses/*id/cohort' => 'courses#list',
          constraints: { id: /.*/ }, via: [:post, :delete]
    match 'courses/*id/tag' => 'courses#tag',
          constraints: { id: /.*/ }, via: [:post, :delete]
    match 'courses/*id/user' => 'users#enroll',
          constraints: { id: /.*/ }, via: [:post, :delete]

    get 'courses/:school/:titleterm(/:endpoint(/*any))' => 'courses#show',
        defaults: { endpoint: 'overview' }, :as => 'show',
        constraints: {
          school: /[^\/]*/,
          titleterm: /[^\/]*/
        }
    post 'clone_course/:id' => 'courses#clone'
  end

  get 'lookups/(:action)(.:format)' => 'lookups'

  # Assigning articles to students
  post 'courses/:course_id/users' => 'users#save_assignments',
       constraints: { course_id: /.*/ }

  # Timeline
  resources :courses, constraints: { id: /.*/ } do
    resources :weeks, only: [:index, :new, :create], constraints: { id: /.*/ }
    # get 'courses' => 'courses#index'
  end
  resources :weeks, only: [:show, :edit, :update, :destroy]
  resources :blocks, only: [:show, :edit, :update, :destroy]
  resources :gradeables, collection: { update_multiple: :put }
  post 'courses/:course_id/timeline' => 'timeline#update_timeline',
       constraints: { course_id: /.*/ }
  post 'courses/:course_id/gradeables' => 'timeline#update_gradeables',
       constraints: { course_id: /.*/ }

  get 'revisions' => 'revisions#index'

  resources :weeks, only: [:index]
  resources :courses_users, only: [:index]

  # Article Finder
  if ENV['dashboard_url'] == 'outreachdashboard.wmflabs.org'
    get 'article_finder(/*any)' => 'article_finder#index'
    post 'article_finder(/*any)' => 'article_finder#results'
  end

  # Reports and analytics
  get 'analytics(/*any)' => 'analytics#index'
  post 'analytics(/*any)' => 'analytics#results'

  # Recent Activity
  get 'recent-activity(/*any)' => 'recent_activity#index'

  # Revision analytics JSON API for React
  get 'revision_analytics/dyk_eligible',
      controller: 'revision_analytics',
      action: 'dyk_eligible'
  get 'revision_analytics/suspected_plagiarism',
      controller: 'revision_analytics',
      action: 'suspected_plagiarism'
  get 'revision_analytics/recent_edits',
      controller: 'revision_analytics',
      action: 'recent_edits'

  # Wizard
  get 'wizards' => 'wizard#wizard_index'
  get 'wizards/:wizard_id' => 'wizard#wizard'
  post 'courses/:course_id/wizard/:wizard_id' => 'wizard#submit_wizard',
       constraints: { course_id: /.*/ }

  # Misc
  get 'courses' => 'courses#index'
  get 'talk' => 'courses#talk'
  # get 'courses/*id' => 'courses#show', :as => :show, constraints: { id: /.*/ }

  # ask.wikiedu.org search box
  get 'ask' => 'ask#search'

  # Root
  root to: 'courses#index'

  # Route aliases for React frontend
  get '/course_creator(/*any)' => 'courses#index'

  # Errors
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/article_finder_controller.rb
require "#{Rails.root}/lib/importers/category_importer"

#= Controller for Article Finder tool
class ArticleFinderController < ApplicationController
  DEFAULT_MAX_WP10_SCORE = 100

  def index
  end

  def results
    @articles = []
    return unless params[:category]
    @category = params[:category]
    cat_name = 'Category:' + @category
    @depth = params[:depth].to_i
    @min_views = params[:minviews].to_i
    @max_wp10 = (params[:maxwp10] || DEFAULT_MAX_WP10_SCORE).to_i
    @articles = CategoryImporter.show_category(cat_name, depth: @depth,
                                                         min_views: @min_views,
                                                         max_wp10: @max_wp10)
    render 'index'
  end
end

app/views/article_finder/_row.html.erb
<li class="row course-list__row">
  <%= link_to article_url(article) do %>
  <div class="row__wrapper">
    <div class="course-list__row__title"><p class="title"><%= full_title(article) %></p></div>
    <div class="course-list__row__revisions"><p><%= article.average_views %></p></div>
    <div class="course-list__row__revisions"><p><%= article.revisions.last.wp10 %></p></div>
  </div>
  <% end %>
</li>

app/views/article_finder/index.html.erb
<% content_for :after_title do " - Article Finder" end %>
<header class="main-page">
  <div class="container">
    <h1>Article Finder <%= @category %></h1>
  </div>
</header>
<div class="container">
<section>
<div class="section-header">
<h3><%= form_tag(method: 'post') do %>
  Put in a category name, excluding the prefix, like "Feminism"<br/><br/>
  <%= label_tag(:category, "category") %>
  <%= text_field_tag(:category, @category) %><br/>
  <%= label_tag(:depth, "depth") %>
  <%= text_field_tag(:depth) %><br/>
  <%= label_tag(:minviews, "minimum views") %>
  <%= text_field_tag(:minviews, @min_views) %><br/>
  <%= label_tag(:maxwp10, "maximum completeness (0-100)") %>
  <%= text_field_tag(:maxwp10, @max_wp10) %><br/>
  <button class="button dark"><%= submit_tag("Go") %></button>
<% end %></h3>
</div>
<% if @articles %>
<div>
  <ul class="list">
    <li class="row course-list__row">Title, Average Views, Completeness</li>
    <% @articles.each do |article| %>
      <%= render :partial => 'row', :locals => {:article => article} %>
    <% end %>
  </ul>
</div>
<% end %>
</section>
</div>

app/views/article_finder/results.html.erb
<% content_for :after_title do " - Article Finder" end %>
<header class="main-page">
  <div class="container">
    <h1>Ohai <%= @category %></h1>
  </div>
</header>