config/routes.rb
# Page titles on Wikipedia may include dots, so this constraint is needed.

Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  # Sessions
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    get 'sign_out', to: 'users#signout', as: :destroy_user_session
    get 'sign_out_oauth', to: 'devise/sessions#destroy',
                          as: :true_destroy_user_session
  end

  # Users
  controller :users do
    get 'users/revisions' => 'users#revisions', :as => :user_revisions
  end

  resources :assignments

  # Self-enrollment: joining a course by entering a passcode or visiting a url
  get 'courses/:course_id/enroll/:passcode' => 'self_enrollment#enroll_self',
      constraints: { course_id: /.*/ }

  # Courses
  controller :courses do
    get 'courses/*id/get_wiki_top_section' => 'courses#get_wiki_top_section',
        :as => :get_wiki_top_section, constraints: { id: /.*/ }
    get 'courses/new' => 'courses#new',
        constraints: { id: /.*/ } # repeat of resources

    get 'courses/*id/manual_update' => 'courses#manual_update',
        :as => :manual_update, constraints: { id: /.*/ }
    get 'courses/*id/notify_untrained' => 'courses#notify_untrained',
        :as => :notify_untrained, constraints: { id: /.*/ }
    get 'courses/*id/notify_students(/:type)' => 'courses#notify_students',
        :as => :notify_students, constraints: { id: /.*/ }
    get 'courses/*id/update_course_talk' => 'courses#update_course_talk',
        :as => :update_course_talk, constraints: { id: /.*/ }

    get 'courses/*id/check' => 'courses#check',
        :as => :check, constraints: { id: /.*/ }
    match 'courses/*id/cohort' => 'courses#list',
          constraints: { id: /.*/ }, via: [:post, :delete]
    match 'courses/*id/tag' => 'courses#tag',
          constraints: { id: /.*/ }, via: [:post, :delete]
    match 'courses/*id/user' => 'users#enroll',
          constraints: { id: /.*/ }, via: [:post, :delete]

    get 'courses/:school/:titleterm(/:endpoint(/*any))' => 'courses#show',
        defaults: { endpoint: 'overview' }, :as => 'show',
        constraints: {
          school: /[^\/]*/,
          titleterm: /[^\/]*/
        }
    post 'clone_course/:id' => 'courses#clone'
  end

  get 'lookups/(:action)(.:format)' => 'lookups'

  # Assigning articles to students
  post 'courses/:course_id/users' => 'users#save_assignments',
       constraints: { course_id: /.*/ }

  # Timeline
  resources :courses, constraints: { id: /.*/ } do
    resources :weeks, only: [:index, :new, :create], constraints: { id: /.*/ }
    # get 'courses' => 'courses#index'
  end
  resources :weeks, only: [:show, :edit, :update, :destroy]
  resources :blocks, only: [:show, :edit, :update, :destroy]
  resources :gradeables, collection: { update_multiple: :put }
  post 'courses/:course_id/timeline' => 'timeline#update_timeline',
       constraints: { course_id: /.*/ }
  post 'courses/:course_id/gradeables' => 'timeline#update_gradeables',
       constraints: { course_id: /.*/ }

  get 'revisions' => 'revisions#index'

  resources :weeks, only: [:index]
  resources :courses_users, only: [:index]

  # Article Finder
  if ENV['dashboard_url'] == 'outreachdashboard.wmflabs.org'
    get 'article_finder(/*any)' => 'article_finder#index'
    post 'article_finder(/*any)' => 'article_finder#results'
  end

  # Reports and analytics
  get 'analytics(/*any)' => 'analytics#index'
  post 'analytics(/*any)' => 'analytics#results'

  # Recent Activity
  get 'recent-activity(/*any)' => 'recent_activity#index'

  # Revision analytics JSON API for React
  get 'revision_analytics/dyk_eligible',
      controller: 'revision_analytics',
      action: 'dyk_eligible'
  get 'revision_analytics/suspected_plagiarism',
      controller: 'revision_analytics',
      action: 'suspected_plagiarism'
  get 'revision_analytics/recent_edits',
      controller: 'revision_analytics',
      action: 'recent_edits'

  # Wizard
  get 'wizards' => 'wizard#wizard_index'
  get 'wizards/:wizard_id' => 'wizard#wizard'
  post 'courses/:course_id/wizard/:wizard_id' => 'wizard#submit_wizard',
       constraints: { course_id: /.*/ }

  # Misc
  get 'courses' => 'courses#index'
  get 'talk' => 'courses#talk'
  # get 'courses/*id' => 'courses#show', :as => :show, constraints: { id: /.*/ }

  # ask.wikiedu.org search box
  get 'ask' => 'ask#search'

  # Root
  root to: 'courses#index'

  # Route aliases for React frontend
  get '/course_creator(/*any)' => 'courses#index'

  # Errors
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/courses_controller.rb
require 'oauth'
require "#{Rails.root}/lib/wiki_edits"

#= Controller for course functionality
class CoursesController < ApplicationController
  include CourseHelper
  respond_to :html, :json
  before_action :require_permissions, only: [:create, :update, :destroy, :notify_untrained]

  ###############
  # Root method #
  ###############
  def index
    cohort = params[:cohort] || ENV['default_cohort']
    @presenter = HomePagePresenter.new(current_user, cohort)
    fail ActionController::RoutingError
      .new('Not Found'), 'Cohort does not exist' unless @presenter.cohort
  end

  ################
  # CRUD methods #
  ################

  def create
    handle_instructor_info if should_update_instructor_info?
    slug_from_params if should_set_slug?
    @course =
      Course.create(course_params.merge('passcode' => Course.generate_passcode))
    handle_timeline_dates
    CoursesUsers.create(user: current_user,
                        course: @course,
                        role: CoursesUsers::Roles::INSTRUCTOR_ROLE)
  end

  def update
    validate
    handle_course_announcement(@course.instructors.first)
    handle_instructor_info
    slug_from_params if should_set_slug?
    handle_timeline_dates
    @course.update course: course_params
    @course.update_attribute(
      :passcode, Course.generate_passcode
    ) if course_params[:passcode].nil?

    WikiEdits.update_course(@course, current_user)
    render json: { course: @course }
  end

  def destroy
    validate
    @course.destroy
    WikiEdits.update_course(@course, current_user, true)
    render json: { success: true }
  end

  ########################
  # View support methods #
  ########################

  def show
    @course = find_course_by_slug("#{params[:school]}/#{params[:titleterm]}")
    check_permission_to_show_course
    respond_to do |format|
      format.html { render }
      format.json { render params[:endpoint] }
    end
  end

  def clone
    course = Course.find(params[:id])
    new_course = CourseCloneManager.new(course, current_user).clone!
    render json: { course: new_course.as_json }
  end

  ##################
  # Helper methods #
  ##################

  def check
    course_exists = Course.exists?(slug: params[:id])
    render json: { course_exists: course_exists }
  end

  def check_permission_to_show_course
    # A user may not see an existing course if it has been de-listed, unless
    # that user in the instructor.
    return if @course.nil?
    return if @course.listed?
    is_instructor = (user_signed_in? && current_user.instructor?(@course))
    return if is_instructor

    fail ActionController::RoutingError
      .new('Not Found'), 'Not permitted'
  end

  def list
    @course = find_course_by_slug(params[:id])
    cohort = Cohort.find_by(title: cohort_params[:title])
    unless cohort
      render json: {
        message: "Sorry, #{cohort_params[:title]} is not a valid cohort."
      }, status: 404
      return
    end
    ListCourseManager.new(@course, cohort, request).manage
  end

  def tag
    @course = find_course_by_slug(params[:id])
    TagManager.new(@course, request).manage
  end

  def manual_update
    @course = find_course_by_slug(params[:id])
    @course.manual_update if user_signed_in?
    render nothing: true, status: :ok
  end
  helper_method :manual_update

  def notify_untrained
    @course = find_course_by_slug(params[:id])
    WikiEdits.notify_untrained(@course.id, current_user)
    render nothing: true, status: :ok
  end
  helper_method :notify_untrained

  private

  def cohort_params
    params.require(:cohort).permit(:title)
  end

  def validate
    slug = params[:id].gsub(/\.json$/, '')
    @course = find_course_by_slug(slug)
    return unless user_signed_in? && current_user.instructor?(@course)
  end

  def should_update_instructor_info?
    (%w(instructor_email instructor_name) & params[:course].keys).any?
  end

  def handle_instructor_info
    return unless should_update_instructor_info?
    c_params = params[:course]
    current_user.real_name =
      c_params['instructor_name'] if c_params.key?('instructor_name')
    current_user.email =
      c_params['instructor_email'] if c_params.key?('instructor_email')
    current_user.save
    c_params.delete('instructor_email')
    c_params.delete('instructor_name')
  end

  def handle_timeline_dates
    @course.timeline_start = @course.start if @course.timeline_start.nil?
    @course.timeline_end = @course.end if @course.timeline_end.nil?
    @course.save
  end

  def handle_course_announcement(instructor)
    newly_submitted = !@course.submitted? && course_params[:submitted] == true
    return unless newly_submitted
    WikiEdits.announce_course(@course, current_user, instructor)
  end

  def should_set_slug?
    %i(title school term).all? { |key| params[:course].key?(key) }
  end

  def slug_from_params(course = params[:course])
    course[:slug] = "#{course[:school]}/#{course[:title]}_(#{course[:term]})"
                    .tr(' ', '_')
  end

  def course_params
    params
      .require(:course)
      .permit(:id, :title, :description, :school, :term, :slug, :subject,
              :expected_students, :start, :end, :submitted, :listed, :passcode,
              :timeline_start, :timeline_end, :day_exceptions, :weekdays,
              :no_day_exceptions, :cloned_status)
  end
end

app/views/courses/_cohort_courses.html.erb
<section id="courses">
  <div class="section-header">
    <h3><%= [t("courses.courses"), presenter.cohort.title].join(" | ") %></h3>
    <div class="sort-select inset">
      <select class="sorts" rel="courses">
        <option rel="asc" value="title"><%= t("courses.title") %></option>
        <option rel="desc" value="revisions"><%= t("metrics.revisions") %></option>
        <option rel="desc" value="characters"><%= t("metrics.characters") %></option>
        <option rel="desc" value="views"><%= t("metrics.view") %></option>
        <option rel="desc" value="students"><%= t("courses.students_short") %></option>
      </select>
    </div>
    <div class="cohort-select">
      <select class="cohorts">
        <option selected disabled><%= t("cohort.view_other") %></option>
        <% Cohort.all.each do |c| %>
          <% unless presenter.cohort.slug == c.slug %>
            <option value="<%= c.slug %>"><%= c.title %></option>
          <% end %>
        <% end %>
        <% if user_signed_in? && current_user.permissions > 0 && presenter.cohort.slug != 'none' %>
          <option value="none">None</option>
        <% end %>
      </select>
    </div>
  </div>
  <div class="row course-list__row list__header">
    <div class="row__wrapper desktop-only-flex">
      <div class="course-list__row__title sort asc" data-sort="title"><p><%= t("courses.courses") %></p></div>

      <div class="course-list__row__revisions sort popover-trigger" data-default-order="desc" data-sort="revisions">
        <p><%= t("metrics.revisions") %></p>
        <div class="popover dark">
          <p><%= t("courses.revisions_doc", timeframe: RevisionStat::REVISION_TIMEFRAME) %></p>
        </div>
      </div>

      <div class="course-list__row__characters sort popover-trigger" data-default-order="desc" data-sort="characters">
        <p><%= t("metrics.char") %></p>
        <div class="popover dark">
          <p><%= t("courses.character_doc") %></p>
        </div>
      </div>
      <div class="course-list__row__views sort popover-trigger" data-default-order="desc" data-sort="views">
        <p><%= t("metrics.view") %></p>
        <div class="popover dark">
          <p><%= t("courses.view_doc") %></p>
        </div>
      </div>
      <div class="course-list__row__students sort" data-default-order="desc" data-sort="students"><p><%= t("users.editors") %></p></div>
    </div>
  </div>
  <ul class="list">
  <% presenter.courses.each do |c| %>
    <%= render 'row', course: c, admin: false, user: false %>
  <% end %>
  </ul>
</section>

app/views/courses/_header_stats.html.erb
<header class="main-page">
  <div class="container">
    <h1><%= Figaro.env.dashboard_title %></h1>
    <div class="stat-display">
      <div class="stat-display__stat">
        <h1><%= presenter.courses.count %></h1>
        <small><%= t("courses.course_description") %></small>
        </div>
      <div class="stat-display__stat popover-trigger">
        <h1><%= presenter.cohort.students_without_nonstudents.count %></h1>
        <small><%= t("courses.students") %></small>
        <div class="popover dark">
          <h4><%= presenter.cohort.trained_count %></h4>
          <p><%= t("users.training_complete", count: presenter.cohort.trained_count) %></p>
        </div>
      </div>
      <div class="stat-display__stat">
        <h1><%= number_to_human presenter.courses.sum(:character_sum) %></h1>
        <small><%= t("metrics.char_added") %></small>
      </div>
      <div class="stat-display__stat">
        <h1><%= number_to_human presenter.courses.sum(:view_sum) %></h1>
        <small><%= t("metrics.view_count_description") %></small>
      </div>
      <div class="stat-display__stat">
        <h1><%= number_to_human presenter.courses.sum(:article_count) %></h1>
        <small><%= "Articles Edited" %></small>
      </div>
      <div class="stat-display__stat">
        <h1><%= number_to_human presenter.courses.sum(:new_article_count) %></h1>
        <small><%= "Articles Created" %></small>
      </div>
    </div>
  </div>
</header>

app/views/courses/_row.html.erb
<li class="row course-list__row">
  <%= link_to course_slug_path(course.slug), 'id' => course.id do %>
    <div class="row__wrapper">
      <div class="course-list__row__title">
        <p class="<%= user ? 'u' : '' %>title"><%= course.title %></p>
      </div>

      <div class="course-list__row__revisions">
        <% revisions = RevisionStat.get_records(course.id) %>
        <p><span class="tablet-only-flex"><%= t("metrics.revisions") %>: </span><%= revisions %></p>
        <p class="<%= user ? 'u' : '' %>revisions hidden"><%= revisions %></p>
      </div>

      <div class="course-list__row__characters">
        <p><span class="tablet-only-flex"><%= t("metrics.char") %>: </span><%= number_to_human course.character_sum %></p>
        <p class="<%= user ? 'u' : '' %>characters hidden"><%= course.character_sum %></p>
      </div>
      <div class="course-list__row__views">
        <p><span class="tablet-only-flex"><%= t("metrics.view") %>: </span><%= number_to_human course.view_sum %></p>
        <p class="<%= user ? 'u' : '' %>views hidden"><%= course.view_sum %></p>
      </div>
      <div class="course-list__row__students">
        <p class="training"><span class="tablet-only-flex"><%= t("users.editors") %>: </span><%= course.user_count %></p>
        <small class="training desktop-only-flex"><%= t("users.training_complete_count", count: course.trained_count) %></small>
        <p class="<%= user ? 'u' : '' %>students hidden"><%= course.user_count %></p>
      </div>
    </div>
  <% end %>
</li>

app/views/courses/_submitted_courses.html.erb
<% if current_user.permissions > 0 && presenter.admin_courses.any? %>
  <section id="admin_courses">
    <div class="section-header">
      <h3>Submitted Courses</h3>
    </div>
    <div class="row course-list__row list__header">
      <div class="row__wrapper desktop-only-flex">
        <div class="course-list__row__long_title sort asc" data-sort="atitle"><p><%= t("courses.courses") %></p></div>
        <div class="course-list__row__link"></div>
      </div>
    </div>
    <ul class="list">
    <% presenter.admin_courses.each do |c| %>
      <%= render 'unapproved_row', course: c, admin: true, user: false %>
    <% end %>
    </ul>
  </section>
<% end %>

app/views/courses/_unapproved_row.html.erb
<li class="row course-list__row">
  <%= link_to course_slug_path(course.slug), 'id' => course.id do %>
    <div class="row__wrapper">
      <div class="course-list__row__long_title">
        <p class="<%= user ? 'u' : admin ? 'a' : '' %>title"><%= course.title %></p>
      </div>
      <div class="course-list__row__link desktop-only-flex">
        <p class="fake-link"><%= t("courses.view") %></p>
      </div>
      <div class="row__fake__link tablet-only"><p class="icon icon-arrow"></p></div>
    </div>
  <% end %>
</li>

app/views/courses/_user_courses.html.erb
<section id="user_courses">
  <div class="section-header">
    <h3><%= t("courses.yourcourses") %></h3>
    <div id="react_root" class="new_course"></div>
  </div>
  <div class="row course-list__row list__header">
    <div class="row__wrapper desktop-only-flex">
      <div class="course-list__row__title sort asc" data-sort="utitle"><p><%= t("courses.courses") %></p></div>

      <div class="course-list__row__revisions sort popover-trigger" data-default-order="desc" data-sort="urevisions">
        <p><%= t("metrics.revisions") %></p>
        <div class="popover dark">
          <p><%= t("courses.revisions_doc", timeframe: RevisionStat::REVISION_TIMEFRAME) %></p>
        </div>
      </div>

      <div class="course-list__row__characters sort popover-trigger" data-default-order="desc" data-sort="ucharacters">
        <p><%= t("metrics.char") %></p>
        <div class="popover dark">
          <p><%= t("courses.character_doc") %></p>
        </div>
      </div>

      <div class="course-list__row__views sort popover-trigger" data-default-order="desc" data-sort="uviews">
        <p><%= t("metrics.view") %></p>
        <div class="popover dark">
          <p><%= t("courses.view_doc") %></p>
        </div>
      </div>

      <div class="course-list__row__students sort" data-default-order="desc" data-sort="ustudents"><p><%= t("users.editors") %></p></div>
    </div>
  </div>
  <ul class="list">
  <% if presenter.user_courses.empty? %>
    <li class="row view-all">
      <div><%= t("courses.nocourses") %></div>
    </li>
  <% else %>
    <% presenter.user_courses.each do |c| %>
      <%= render 'row', course: c, admin: false, user: true %>
    <% end %>
  <% end %>
  </ul>
</section>

app/views/courses/index.html.erb
<% content_for :after_title do " - #{@presenter.cohort.title}" end %>

<%= render 'header_stats', presenter: @presenter %>

<div class="container">
  <% if user_signed_in? %>
    <%= render 'submitted_courses', presenter: @presenter %>
    <%= render 'user_courses', presenter: @presenter %>
  <% end %>

  <%= render 'cohort_courses', presenter: @presenter %>
</div>

app/views/courses/new.html.erb
<% content_for :after_title do " - Create New Course" end %>

<header class="main-page">
  <h1><%= Figaro.env.dashboard_title %></h1>
</header>

<section id="courses">
  <div class="section-header">
    <% if flash[:notice] %>
      <div class="alert"><p><%= flash[:notice] %></p></div>
    <% end %>
    <h3>Create New Course</h3>
    <%= form_for :course, url: courses_path do |f| %>
      <fieldset>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </fieldset>

      <fieldset>
        <%= f.label :description %>
        <%= f.text_area :description %>
      </fieldset>

      <fieldset>
        <%= f.label :school %>
        <%= f.text_field :school %>
      </fieldset>

      <fieldset>
        <%= f.label :term %>
        <%= f.text_field :term %>
      </fieldset>

      <fieldset>
        <%= f.label :subject %>
        <%= f.text_field :subject %>
      </fieldset>

      <fieldset>
        <%= f.label :expected_students %>
        <%= f.text_field :expected_students %>
      </fieldset>

      <fieldset>
        <%= f.label :start %>
        <%= f.date_field :start %>
        <%= f.label :end %>
        <%= f.date_field :end %>
      </fieldset>

      <fieldset>
        <%= f.submit %>
      </fieldset>
    <% end %>
  </div>
</section>

app/views/courses/show.html.erb
<div id="react_root" data-current_user="<%= user_signed_in? ? current_user.roles(@course).to_json : { admin: false, id: nil } %>"></div>

app/views/courses/wikitext.html.erb
<%= "#{@course.title}" %>
<%= "#{@course.description}" %>